# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
r:
  - release
  - devel

warnings_are_errors: true
sudo: true
cache: packages

before_install:
  - sudo apt-get install libmpfr-dev

r_packages:
  - covr
  - Rmpfr

after_success:
  - Rscript --verbose -e 'library(covr); codecov()'

repos:
  CRAN: https://cloud.r-project.org

notifications:
  email:
    recipients:
      - siegfried.koestlmeier@gmail.com
    on_success: always
    on_failure: always
